### ISSUE TITLE
how is fb_id generated

### ISSUE THREAD

**Issue by scoarescoare** [auth0/mdocs2#3]
There are [multiple references](https://github.com/auth0/mdocs2/blob/gh-pages/client_side/docs.js#L32) to the `fb_id` property. I cannot figure out how it's being populated. Is it  a rule setup in this particular auth0 app to attach this property to the user profile?

**Comment by jfromaniello** [comment]
Sorry I didn't get the notfication from github,

It is being created on an auth0 rule. I will add this info tomorrow and let you know

**Comment by jfromaniello** [comment]
Hi @scoarescoare sorry for the delay. I just added a wiki page explaining how to configure firebase and auth0 for mdocs:

https://github.com/auth0/mdocs2/wiki/Configuration

**Comment by scoarescoare** [comment]
Ah, perfect, thank you! I had assumed it was something similar to that, but
this is much clearer to me now :)
